### ISSUE TITLE
Dynamic URL Caching

### ISSUE THREAD

**Issue by sisindrymedagam** [eneajaho/ngx-isr#19]
How to Cache dynamic Content using ngc-irs?

I have used like this

```js
const routes: Routes = [
  { path: ':slug', component: PsingleComponent, data: { revalidate: 60 } }
];
```
How ever its not cached all the content in html page, it just cached the Skeleton.

**Comment by eneajaho** [comment]
Hello @sisindrymedagam 

As you can see also in the [ngx-isr-demo project ](https://github.com/eneajaho/ngx-isr/tree/main/projects/ngx-isr-demo) in the [routes](https://github.com/eneajaho/ngx-isr/blob/14f4954e9a95f8e61caf634a552d18ac45c51961/projects/ngx-isr-demo/src/app/routes.ts#L33) file.

So just like this: 

```js
{
  path: "details/:id",
  component: DetailsComponent,
  data: { revalidate: 10 }
}
```

If it still doesn't cache the content, please make sure it also is served on first open when using just normal Server side rendering.

Last resort would be to provide a reproduction repo in order to check it further.

Thanks
